console.time("your code took");
console.log("hello console");
console.log(45 + 56);
console.log(true);
console.log([34, 2, 5, 8]);
console.log({ abhishek: "this", marks: 34 });
console.table({ abhishek: "this", marks: 34 });
console.warn("this is warning");
console.timeEnd("your code took");
// console.assert(566 < 189, "Age > 189 is not possible");
console.error("this is an error");
