console.log("this is tutorial 11");
let a = window.document;
// window.alert("hello harry");
// a = prompt("this will destroy your computer");
// a = confirm("are you sure you want to delete this page?");
a = window.innerHeight;
a = innerWidth;
a = scrollX;
a = scrollY;
a = location.toString();
a = window.history;
console.log(a);
